---
score: 60
roomID: Y2lzY29zcGFyazovL3VzL1JPT00vNWNiYjZmZTAtM2RiNy0xMWVjLWIwZWUtNmI5N2MzZWM2NTk2
bot_token: Mjc4ZjAxMzYtOWNmZS00NmEzLWEzMTMtN2FmNDdkNDAwYTczYzg2ZmI3NjItZmQx_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f